Repository IS-200-G7/nordicdoor, pull requests merged in 2022-10, with the labels that each got.

#6 Create dotnet.yml
  .github/workflows/dotnet.yml
Labels: help wanted, hacktoberfest-accepted

#11 Auth controller
  PDSA_System/Server/Controllers/AuthController.cs
  PDSA_System/Server/Models/Bruker.cs
  PDSA_System/Server/Models/JwtClaims.cs
  PDSA_System/Server/Models/LoginFormData.cs
  PDSA_System/Server/PDSA_System.Server.csproj
  PDSA_System/Server/PasswordHash.cs
Labels: Prioritet 1

#12 Legge til Swagger som et debugging-verktøy. Er tilgjengelig på /swagger
  PDSA_System/Server/PDSA_System.Server.csproj
  PDSA_System/Server/Program.cs
Labels: enhancement

#15 use DATETIME instead of DATE
  PDSA_System/Server/DataBase/Create.sql
Labels: enhancement, hacktoberfest-accepted

#16 Login form
  PDSA_System/Client/Pages/Login.razor
  PDSA_System/Client/Shared/SubmitInput.razor
  PDSA_System/Client/Shared/TextInput.razor
  PDSA_System/Client/models/LoginData.cs
  PDSA_System/Client/wwwroot/index.html
  PDSA_System/Server/Controllers/AuthController.cs
Labels: Prioritet 1

#26 Automatisk laging av database og bruk IF NOT EXISTS når man lager tabeller
  PDSA_System/Server/DataBase/Create.sql
Labels: hacktoberfest-accepted

#36 Use story 2
  PDSA_System/Server/Controllers/BrukerController.cs
  PDSA_System/Server/Controllers/TeamController.cs
  PDSA_System/Server/DataBase/Create.sql
  PDSA_System/Server/Models/Bruker.cs
  PDSA_System/Server/Models/Team.cs
  PDSA_System/Server/Models/TeamMedlemskap.cs
  PDSA_System/Server/appsettings.json
Labels: Prioritet 1

#45 added StatusController.cs
  PDSA_System/Server/Controllers/StatusController.cs
Labels: Prioritet 1

#47 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#58 Forslag controller
  PDSA_System/Server/Controllers/ForslagController.cs
  PDSA_System/Server/Models/Forslag.cs
Labels: enhancement

#64 Funksjon for å hente ut alle forslag til spesifikke brukere, og tweak av Update slik at den funker
  PDSA_System/Server/Controllers/ForslagController.cs
  PDSA_System/Server/Models/Forslag.cs
Labels: enhancement

#69 DB attributt fix og mer seedData
  PDSA_System/Server/DataBase/Create.sql
  PDSA_System/Server/DataBase/addSeedData.sql
Labels: enhancement

#76 Formatering med .editorconfig
  PDSA_System/Client/Pages/Forslag/ForslagOverview.razor
  PDSA_System/Client/Shared/NavMenu.razor
  PDSA_System/Server/Controllers/BrukerController.cs
  PDSA_System/Server/Controllers/ForslagController.cs
  PDSA_System/Server/Controllers/TeamController.cs
  PDSA_System/Server/DataBase/Create.sql
  PDSA_System/Server/DataBase/addSeedData.sql
  PDSA_System/Server/Models/Bruker.cs
  PDSA_System/Server/Models/JwtClaims.cs
  PDSA_System/Server/Models/Team.cs
  PDSA_System/Server/Models/TeamMedlemskap.cs
  PDSA_System/Server/appsettings.json
  PDSA_System/Server/package-documentation/Dapper.md
  PDSA_System/Server/package-documentation/Jwt.md
  PDSA_System/Shared/Models/Forslag.cs
Labels: enhancement

#74 Auth fix
  PDSA_System/Client/PDSA_System.Client.csproj
  PDSA_System/Server/Controllers/AuthController.cs
  PDSA_System/Server/Controllers/DebugController.cs
  PDSA_System/Server/Models/JwtClaims.cs
  PDSA_System/Server/Program.cs
  PDSA_System/Server/appsettings.json
Labels: Prioritet 1
